### PR TITLE
Add example for separate bull producer and consumer nest processes/apps

### PR DESCRIPTION
**Pull request by tak1n**
Created the apps with `nx g @nrwl/nest:app`. Let me know what you think :v:

### CODE REVIEW

**Comment by tak1n** [comment]
@jmcdo29 should I add a docker-compose for redis?

**Comment by jmcdo29** [comment]
Overall looks good, clean, and easy to work with. A docker-compose for redis would be great, along with maybe some information about how to run the two applications, but overall it looks good

**Comment by tak1n** [comment]
> Overall looks good, clean, and easy to work with. A docker-compose for redis would be great, along with maybe some information about how to run the two applications, but overall it looks good

Done

**Review by jmcdo29 — APPROVED** [review]

**Comment by jmcdo29** [comment]
Sweet! Thanks for the addition!

**Pull request merged**
